class Command:
    HELP = "__help"
    MENU = "__menu"
    POINT = "__point"
    LAST_SENT = "__last_sent"
    LAST_RECEIVED = "__last_received"
    MESSAGE_LIST = "__message_list"
    FINISH_TRANSACTION = "__finish_transaction"
    QUICK_REPLY = "__quick_reply"
    TRANSACTION_COUNT = "__transaction_count"
    TOP_TEN = "__top_ten"
    SEND_MESSAGE_ALL = "__send_message_all"
    GET_TRANSACTION_REPORT = "__get_transaction_report"
    ADD_USER = "__add_user"
    REMOVE_USER = "__remove_user"
