class Globals:
    LOAD_BALANCE_CRON = "* * * * 1"
    RESET_BALANCE_CRON = "* * 1 * *"
    LOAD_BALANCE_TIME = "08:05"
    RESET_BALANCE_TIME = "08:00"
    BIRTHDAY_MSG_TIME = "08:30"
    SPECIAL_DATE_MSG_TIME = "09:00"
    LOAD_BALANCE_AMOUNT = 200
    SEND_SAME_PERSON_LIMIT = 3
    SEND_SAME_TEAM_LIMIT = 10
    SEND_AMOUNT = 10
    EARN_AMOUNT = 1
    DEFAULT_PASSWD = "123456"
    DELIMITER = ":::"


class Role:
    USER = "USER"
    SCOPE_ADMIN = "SCOPE_ADMIN"
    SUPER_ADMIN = "SUPER_ADMIN"
